services:
  postgres:
    image: postgres:15
    container_name: horizon_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"  # Исправлено на 54322 для соответствия коду
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: