// Экспортируем все схемы из локальной директории
export * from './users.js';
export * from './departments.js';
export * from './characters.js';
export * from './applications.js';
export * from './supportTickets.js';
export * from './vehicles.js';
export * from './weapons.js';
export * from './activeUnits.js';
export * from './call911.js';
export * from './reports.js';
export * from './ranks.js';
export * from './forumCategories.js';
export * from './forumTopics.js';
export * from './forumPosts.js';
export * from './forumReactions.js';
export * from './forumSubscriptions.js';
export * from './forumViews.js';
export * from './forumStats.js';

// Создаем локальные типы из схем
import { users } from './users.js';
import { departments } from './departments.js';
import { characters } from './characters.js';
import { applications } from './applications.js';
import { supportTickets } from './supportTickets.js';
import { vehicles } from './vehicles.js';
import { weapons } from './weapons.js';
import { activeUnits } from './activeUnits.js';
import { call911 } from './call911.js';
import { reports } from './reports.js';
import { ranks } from './ranks.js';
import { forumCategories } from './forumCategories.js';
import { forumTopics } from './forumTopics.js';
import { forumPosts } from './forumPosts.js';
import { forumReactions } from './forumReactions.js';
import { forumSubscriptions } from './forumSubscriptions.js';
import { forumViews } from './forumViews.js';
import { forumStats } from './forumStats.js';

// Локальные типы для избежания конфликтов версий
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type Department = typeof departments.$inferSelect;
export type InsertDepartment = typeof departments.$inferInsert;
export type Character = typeof characters.$inferSelect;
export type InsertCharacter = typeof characters.$inferInsert;
export type Application = typeof applications.$inferSelect;
export type InsertApplication = typeof applications.$inferInsert;
export type SupportTicket = typeof supportTickets.$inferSelect;
export type InsertSupportTicket = typeof supportTickets.$inferInsert;
export type Vehicle = typeof vehicles.$inferSelect;
export type InsertVehicle = typeof vehicles.$inferInsert;
export type Weapon = typeof weapons.$inferSelect;
export type InsertWeapon = typeof weapons.$inferInsert;
export type ActiveUnit = typeof activeUnits.$inferSelect;
export type InsertActiveUnit = typeof activeUnits.$inferInsert;
export type Call911 = typeof call911.$inferSelect;
export type InsertCall911 = typeof call911.$inferInsert;
export type Report = typeof reports.$inferSelect;
export type InsertReport = typeof reports.$inferInsert;
export type Rank = typeof ranks.$inferSelect;
export type InsertRank = typeof ranks.$inferInsert;
export type ForumCategory = typeof forumCategories.$inferSelect;
export type InsertForumCategory = typeof forumCategories.$inferInsert;
export type ForumTopic = typeof forumTopics.$inferSelect;
export type InsertForumTopic = typeof forumTopics.$inferInsert;
export type ForumPost = typeof forumPosts.$inferSelect;
export type InsertForumPost = typeof forumPosts.$inferInsert;
export type ForumReaction = typeof forumReactions.$inferSelect;
export type InsertForumReaction = typeof forumReactions.$inferInsert;
export type ForumSubscription = typeof forumSubscriptions.$inferSelect;
export type InsertForumSubscription = typeof forumSubscriptions.$inferInsert;
export type ForumView = typeof forumViews.$inferSelect;
export type InsertForumView = typeof forumViews.$inferInsert;
export type ForumStats = typeof forumStats.$inferSelect;
export type InsertForumStats = typeof forumStats.$inferInsert; 