console.log('🔍 Проверка localStorage в браузере:');
console.log('=====================================');
console.log('');
console.log('1️⃣ Откройте браузер и перейдите на http://localhost:5173');
console.log('');
console.log('2️⃣ Откройте консоль разработчика (F12)');
console.log('');
console.log('3️⃣ Войдите как candidate@horizon.com');
console.log('');
console.log('4️⃣ Выполните следующие команды в консоли:');
console.log('');
console.log('   // Проверить все ключи localStorage');
console.log('   Object.keys(localStorage)');
console.log('');
console.log('   // Проверить токен аутентификации');
console.log('   localStorage.getItem("auth_token")');
console.log('');
console.log('   // Проверить пользователя');
console.log('   localStorage.getItem("auth_user")');
console.log('');
console.log('   // Проверить другие возможные ключи');
console.log('   localStorage.getItem("authToken")');
console.log('   localStorage.getItem("mockToken")');
console.log('');
console.log('5️⃣ Если токен найден, проверьте API:');
console.log('');
console.log('   fetch("/api/application-limits/entry", {');
console.log('     headers: {');
console.log('       "Authorization": "Bearer " + localStorage.getItem("auth_token")');
console.log('     }');
console.log('   }).then(r => r.json()).then(console.log)');
console.log('');
console.log('=====================================');
console.log('✅ После этих действий мы увидим, работает ли аутентификация!'); 