console.log('🧹 Инструкция по очистке кэша браузера:');
console.log('=====================================');
console.log('');
console.log('1️⃣ Откройте браузер и перейдите на http://localhost:5173');
console.log('');
console.log('2️⃣ Откройте консоль разработчика (F12)');
console.log('');
console.log('3️⃣ Выполните следующие команды в консоли:');
console.log('');
console.log('   // Очистить localStorage');
console.log('   localStorage.clear();');
console.log('');
console.log('   // Очистить sessionStorage');
console.log('   sessionStorage.clear();');
console.log('');
console.log('   // Очистить кэш React Query (если доступен)');
console.log('   if (window.__REACT_QUERY_GLOBAL_CACHE__) {');
console.log('     window.__REACT_QUERY_GLOBAL_CACHE__.clear();');
console.log('   }');
console.log('');
console.log('4️⃣ Перезагрузите страницу (Ctrl+Shift+R)');
console.log('');
console.log('5️⃣ Войдите заново как candidate@horizon.com');
console.log('');
console.log('6️⃣ Проверьте кнопку "Подать заявку на вступление"');
console.log('');
console.log('=====================================');
console.log('✅ После этих действий кнопка должна стать активной!'); 