name: Deploy to VPS (Optimized)

on:
  push:
    branches:
      - main
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build:production
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Create deployment package
        run: |
          # Создаем архив только с необходимыми файлами (без node_modules и env.example)
          tar -czf deployment.tar.gz \
            dist/ \
            package.json \
            package-lock.json \
            scripts/ \
            public/ \
            supabase/ \
            migrations/ \
            docs/ \
            README.md

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "deployment.tar.gz"
          target: "/var/www/app"
          strip_components: 0

      - name: Setup and restart application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Переходим в директорию приложения
            cd /var/www/app
            
            # Распаковываем архив
            tar -xzf deployment.tar.gz
            
            # Создаем .env из GitHub Secrets
            echo "🔐 Создаем .env из GitHub Secrets..."
            echo "NODE_ENV=production" > .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
            echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
            echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
            echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
            
            # Создаем ecosystem файл для PM2
            echo "📝 Создаем ecosystem файл для PM2..."
            cat > ecosystem.config.js << 'EOL'
            module.exports = {
              apps: [{
                name: 'roleplayidentity',
                script: 'dist/index.js',
                env: {
                  NODE_ENV: 'production',
                  PORT: '${{ secrets.PORT }}',
                  SUPABASE_URL: '${{ secrets.SUPABASE_URL }}',
                  SUPABASE_ANON_KEY: '${{ secrets.SUPABASE_ANON_KEY }}',
                  SUPABASE_SERVICE_ROLE_KEY: '${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}',
                  DATABASE_URL: '${{ secrets.DATABASE_URL }}',
                  JWT_SECRET: '${{ secrets.JWT_SECRET }}',
                  VITE_SUPABASE_URL: '${{ secrets.VITE_SUPABASE_URL }}',
                  VITE_SUPABASE_ANON_KEY: '${{ secrets.VITE_SUPABASE_ANON_KEY }}'
                }
              }]
            };
            EOL
            
            # Безопасный рестарт приложения
            if pm2 list | grep -q "roleplayidentity"; then
              echo "🔄 Перезапускаем приложение..."
              pm2 delete roleplayidentity
            fi
            
            echo "🚀 Запускаем приложение с ecosystem файлом..."
            pm2 start ecosystem.config.js
            
            # Сохраняем конфигурацию PM2
            pm2 save
            
            # Проверяем статус
            echo "📊 Статус приложения:"
            pm2 status
            
            # Очищаем архив
            rm -f deployment.tar.gz
            
            echo "✅ Деплой завершен успешно!"

      - name: Health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Ждем немного для запуска приложения
            sleep 5
            
            # Проверяем статус PM2
            pm2 status
            
            # Проверяем доступность приложения
            if curl -f http://localhost:5000/api/health > /dev/null 2>&1; then
              echo "✅ Приложение доступно на localhost:5000"
            else
              echo "❌ Приложение недоступно на localhost:5000"
              echo "📋 Логи приложения:"
              pm2 logs roleplayidentity --lines 10 --nostream
              exit 1
            fi 